import { useEffect, useState, type FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from './components/ui/button';
import { Card } from './components/ui/card';
import { TrafficChart } from './components/dashboard/traffic-chart';
import { FluxScaleMark } from './components/brand/fluxscale-mark';
import './connected.css';

type Policy = { enabled: boolean; min_replicas: number; max_replicas: number; version: number };
type Metric = { timestamp: string; requests_per_second: number; p95_latency_ms: number; error_rate: number; cpu_percent: number; memory_percent: number };
type Project = { id: string; name: string; service: string; policy: Policy };
type Detail = Project & { host: null | { id: string; online: boolean; last_seen: number; applied_version: number; snapshot: null | { ready: boolean; error: string | null; metrics: Metric[]; backends: { container_name: string; healthy: boolean; draining: boolean; in_flight: number }[]; decisions: { timestamp: string; action: string; desired_replicas: number }[] } } };
type Session = { email: string; csrf: string };
async function request<T>(path: string, method = 'GET', data?: unknown, csrf?: string): Promise<T> {
  const response = await fetch(path, { method, credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(csrf ? { 'X-CSRF-Token': csrf } : {}) }, body: data === undefined ? undefined : JSON.stringify(data) });
  const result = await response.json(); if (!response.ok) { if (response.status === 401 && !path.startsWith('/api/auth/')) window.dispatchEvent(new Event('fluxscale-session-expired')); throw new Error(result.error ?? `Request failed (${response.status})`); } return result as T;
}
export default function ConnectedApp() {
  const cache = useQueryClient(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [selected, select] = useState(''); const [enrollment, setEnrollment] = useState<{ project: string; token: string } | null>(null);
  const [register, setRegister] = useState(false);
  useEffect(() => { const expired = () => { cache.clear(); setEnrollment(null); }; window.addEventListener('fluxscale-session-expired', expired); return () => window.removeEventListener('fluxscale-session-expired', expired); }, [cache]);
  const session = useQuery({ queryKey: ['connected-session'], queryFn: () => request<Session>('/api/auth/me'), retry: false, refetchInterval: 60000 });
  const projects = useQuery({ queryKey: ['connected-projects', session.data?.email], queryFn: () => request<Project[]>('/api/projects'), enabled: !!session.data, retry: false, refetchInterval: 5000 });
  const id = projects.data?.some(p => p.id === selected) ? selected : projects.data?.[0]?.id;
  const detail = useQuery({ queryKey: ['connected-project', session.data?.email, id], queryFn: () => request<Detail>(`/api/projects/${id}`), enabled: !!session.data && !!id, retry: false, refetchInterval: 5000 });
  const audit = useQuery({ queryKey: ['connected-audit', session.data?.email], queryFn: () => request<{ project_id: string; event: string; at: number }[]>('/api/audit'), enabled: !!session.data, retry: false, refetchInterval: 10000 });
  async function action(operation: () => Promise<void>) { setBusy(true); setError(''); try { await operation(); await cache.invalidateQueries({ queryKey: ['connected-projects'] }); await cache.invalidateQueries({ queryKey: ['connected-project'] }); await cache.invalidateQueries({ queryKey: ['connected-audit'] }); } catch (e) { setError(e instanceof Error ? e.message : 'Request failed'); } finally { setBusy(false); } }
  function form(event: FormEvent<HTMLFormElement>) { event.preventDefault(); return new FormData(event.currentTarget); }
  function login(event: FormEvent<HTMLFormElement>) { const data = form(event); void action(async () => { const result = await request<Session>(register ? '/api/auth/register' : '/api/auth/login', 'POST', Object.fromEntries(data)); cache.setQueryData(['connected-session'], result); setEnrollment(null); setRegister(false); }); }
  const current = detail.data; const snapshot = current?.host?.snapshot; const latest = snapshot?.metrics.at(-1); const fresh = !!current?.host?.online && !!latest && current.host.last_seen - Date.parse(latest.timestamp) < 30000;
  const traffic = snapshot?.metrics.map(metric => ({ timestamp: metric.timestamp, actual: metric.requests_per_second, predicted: null, capacity: null })) ?? [];
  return <div className="connected-shell">
    <header className="connected-header"><a href="/connected" className="connected-brand"><FluxScaleMark /> <strong>FluxScale</strong> <span>Deployments</span></a>{session.data && <div>{session.data.email} <Button variant="outline" disabled={busy} onClick={() => void action(async () => { await request('/api/auth/logout', 'POST', {}, session.data?.csrf); cache.clear(); setEnrollment(null); })}>Sign out</Button></div>}</header>
    {error && <p role="alert" className="connected-error">{error}</p>}
    {!session.data ? <Card className="connected-login"><h1>{register ? 'Create your account' : 'Sign in to FluxScale'}</h1><p>Connect your deployment and scale actual application containers.</p><form onSubmit={login}>
      <label>Email<input name="email" type="email" autoComplete="username" required maxLength={254} /></label>
      <label>Password<input name="password" type="password" autoComplete={register ? 'new-password' : 'current-password'} required minLength={12} maxLength={128} /></label>
      {register && <label>Invitation code<input name="invite" autoComplete="off" required minLength={43} maxLength={43} /><small>Get a one-use invitation from your FluxScale administrator.</small></label>}
      <Button disabled={busy || session.isPending} type="submit">{busy ? 'Please wait…' : register ? 'Create account' : 'Sign in'}</Button>
    </form><button className="connected-link" onClick={() => setRegister(!register)}>{register ? 'Already have an account? Sign in' : 'Have an invitation? Create account'}</button></Card> : <main>
      <h1>Your deployments</h1><p>Application replicas run on your infrastructure. Each project connects to its own local controller.</p>
      <div className="connected-layout"><aside><Card className="connected-panel"><h2>Projects</h2>{projects.data?.map(p => <button className={p.id === id ? 'connected-project selected' : 'connected-project'} key={p.id} onClick={() => { select(p.id); setEnrollment(null); }}>{p.name}<small>{p.service}</small></button>)}{projects.data?.length === 0 && <p>Create a project to connect your first deployment.</p>}
        <details><summary>Create project</summary><form onSubmit={event => { const data = form(event); void action(async () => { const p = await request<{ id: string }>('/api/projects', 'POST', { name: data.get('name'), service: data.get('service'), policy: { enabled: false, min_replicas: Number(data.get('min')), max_replicas: Number(data.get('max')) } }, session.data?.csrf); select(p.id); }); }}>
          <label>Project name<input name="name" required maxLength={80} /></label><label>Service ID<input name="service" required pattern="[a-zA-Z0-9_.\-]+" maxLength={128} /></label><label>Minimum replicas<input name="min" type="number" min={1} max={100} defaultValue={1} required /></label><label>Maximum replicas<input name="max" type="number" min={1} max={100} defaultValue={3} required /></label><Button disabled={busy}>Create project</Button>
        </form></details></Card></aside>
      <section>{projects.error && <p role="alert">{projects.error.message}</p>}{detail.error && <p role="alert">{detail.error.message}</p>}{current && <>
        <Card className="connected-panel"><h2>{current.name}</h2><p>{current.service} · {current.host ? current.host.online ? 'Host connected' : 'Host offline' : 'No host connected'}</p>
          {current.host && <a data-project-console href={`/projects/${current.id}/console`} className="connected-link">Open FluxScale dashboard</a>}
          <p>Autoscaling {current.policy.enabled ? 'enabled' : 'paused'} · Policy v{current.policy.version} {current.host?.applied_version === current.policy.version ? 'applied' : 'awaiting host acknowledgement'}</p>
          {snapshot?.error && <p role="alert">{snapshot.error}</p>}{current.host && <p>Last report: {current.host.last_seen ? new Date(current.host.last_seen).toLocaleString() : 'Awaiting first report'} · Controller {snapshot?.ready ? 'ready' : 'not ready'}</p>}
          <details><summary>Scaling policy and host connection</summary><form key={`${current.id}:${current.policy.version}`} onSubmit={event => { const data = form(event); void action(async () => { await request(`/api/projects/${id}/policy`, 'POST', { enabled: data.get('enabled') === 'on', min_replicas: Number(data.get('min')), max_replicas: Number(data.get('max')) }, session.data?.csrf); }); }}>
            <div className="connected-fields"><label>Minimum replicas<input name="min" type="number" min={1} max={100} defaultValue={current.policy.min_replicas} required /></label><label>Maximum replicas<input name="max" type="number" min={1} max={100} defaultValue={current.policy.max_replicas} required /></label><label className="connected-checkbox"><input name="enabled" type="checkbox" defaultChecked={current.policy.enabled} />Enable automatic scaling</label></div><Button disabled={busy}>Save policy</Button>
          </form><p><small>Host limits remain authoritative. Pausing prevents new telemetry-driven scaling; existing reconciliation and health repair may finish. During disconnection the host retains its last applied policy.</small></p>
          {!current.host ? <><Button variant="outline" disabled={busy} onClick={() => void action(async () => { const result = await request<{ token: string }>(`/api/projects/${id}/enrollment`, 'POST', {}, session.data?.csrf); setEnrollment({ project: current.id, token: result.token }); })}>Generate host enrollment</Button>{enrollment?.project === current.id && <div><p>Single use, expires in 10 minutes. Treat this code as a secret.</p><input aria-label="Enrollment token" readOnly value={enrollment.token} /><p>Use the connected deployment guide to install the agent on your VM, then provide this code through FLUXSCALE_ENROLLMENT_TOKEN.</p></div>}</> : <Button variant="outline" disabled={busy} onClick={() => { if (window.confirm('Revoke this host connection? Its local controller keeps the last applied policy.')) void action(async () => { await request(`/api/projects/${id}/host`, 'DELETE', undefined, session.data?.csrf); setEnrollment(null); }); }}>Revoke host connection</Button>}
          </details>
        </Card>
        <div className="connected-stats">{[['Traffic', fresh ? `${latest.requests_per_second.toFixed(1)} RPS` : 'Unavailable'], ['P95 latency', fresh ? `${latest.p95_latency_ms.toFixed(0)} ms` : 'Unavailable'], ['Errors', fresh ? `${(latest.error_rate * 100).toFixed(2)}%` : 'Unavailable'], ['Healthy replicas', current.host?.online && snapshot ? String(snapshot.backends.filter(b => b.healthy && !b.draining).length) : 'Unavailable']].map(([label, value]) => <Card className="connected-panel" key={label}><small>{label}</small><strong>{value}</strong></Card>)}</div>
        <Card className="connected-panel"><h2>Traffic history</h2><TrafficChart data={traffic} /><details><summary>Measured samples</summary><div className="connected-table"><table><thead><tr><th>Time</th><th>RPS</th><th>P95 ms</th><th>CPU %</th><th>Memory %</th></tr></thead><tbody>{snapshot?.metrics.slice(-20).reverse().map((m, i) => <tr key={`${m.timestamp}:${i}`}><td>{new Date(m.timestamp).toLocaleTimeString()}</td><td>{m.requests_per_second}</td><td>{m.p95_latency_ms}</td><td>{m.cpu_percent}</td><td>{m.memory_percent}</td></tr>)}</tbody></table></div></details>{!snapshot?.metrics.length && <p>Waiting for real application telemetry. Integrate the SDK and route traffic through the local proxy.</p>}</Card>
        <Card className="connected-panel"><h2>Application containers</h2>{snapshot?.backends.map(b => <p key={b.container_name}><code>{b.container_name}</code> · {b.draining ? 'Draining' : b.healthy ? 'Healthy' : 'Unhealthy'} · {b.in_flight} active requests</p>)}{!snapshot?.backends.length && <p>No managed containers reported.</p>}</Card>
        <Card className="connected-panel"><h2>Scaling decisions</h2>{snapshot?.decisions.slice(-10).reverse().map((d, i) => <p key={`${d.timestamp}:${i}`}>{new Date(d.timestamp).toLocaleTimeString()} · {d.action} · target {d.desired_replicas} replicas</p>)}<small>Decisions are evaluated from telemetry. Actual running replicas are shown above.</small></Card>
      </>}</section></div>
      <Card className="connected-panel"><h2>Account activity</h2>{audit.data?.slice(0, 10).map((entry, i) => <p key={i}>{new Date(entry.at).toLocaleString()} · {entry.event.replaceAll('_', ' ')}</p>)}</Card>
      <details className="connected-panel"><summary>Change password</summary><form onSubmit={event => { const data = form(event); void action(async () => { await request('/api/auth/password', 'POST', Object.fromEntries(data), session.data?.csrf); cache.clear(); setEnrollment(null); }); }}><label>Current password<input type="password" name="current_password" autoComplete="current-password" minLength={12} maxLength={128} required /></label><label>New password<input type="password" name="password" autoComplete="new-password" minLength={12} maxLength={128} required /></label><Button disabled={busy}>Change password and sign out</Button></form></details>
    </main>}
  </div>;
}
